using Cart.API.Common;
using Cart.API.DTO.Response;
using RabbitMQ.Client;
using RabbitMQ.Client.Events;
using System.Collections.Concurrent;
using System.Text;
using System.Text.Json;

namespace Cart.API.Web.AsyncMessageBusServices.Rpc
{
    public class UserRpcClient : IUserRpcClient
    {
        private const string QUEUE_NAME = "userPublishQueue";
        private readonly ConnectionState connectionState;
        private readonly string replyQueueName;
        private readonly EventingBasicConsumer consumer;
        private readonly ConcurrentDictionary<string, TaskCompletionSource<string>> callbackMapper =
                    new ConcurrentDictionary<string, TaskCompletionSource<string>>();

        public UserRpcClient(ConnectionState connectionState)
        {
            this.connectionState = connectionState;

            // declare a server-named queue
            replyQueueName = connectionState.Channel.QueueDeclare(queue: "").QueueName;
            //Queue names starting with "amq." are reserved for public use by the broker.
            //Attempts to declare a queue with a name that violates this rule will result in a channel-level exception with reply code 403 (ACCESS_REFUSED).
            //For the communication to work, the name should be "", as the rpc queuename is autogenerated and starting with "amq."

            consumer = new EventingBasicConsumer(connectionState.Channel);
            consumer.Received += (model, ea) =>
            {
                if (!callbackMapper.TryRemove(ea.BasicProperties.CorrelationId, out TaskCompletionSource<string> tcs))
                {
                    return;
                }
                var body = ea.Body.ToArray();
                var response = Encoding.UTF8.GetString(body);
                tcs.TrySetResult(response);
            };

            connectionState.Channel.BasicConsume(
              consumer: consumer,
              queue: replyQueueName,
              autoAck: true);
        }

        private Task<string> AcquireUserBalanceInfo(string message, CancellationToken cancellationToken = default(CancellationToken)) // default - empty canc token
        {
            IBasicProperties props = connectionState.Channel.CreateBasicProperties();
            var correlationId = Guid.NewGuid().ToString();
            props.CorrelationId = correlationId;
            props.ReplyTo = replyQueueName;
            var messageBytes = Encoding.UTF8.GetBytes(message);
            var tcs = new TaskCompletionSource<string>();
            callbackMapper.TryAdd(correlationId, tcs);

            connectionState.Channel.BasicPublish(
               exchange: "",
               routingKey: QUEUE_NAME,
               basicProperties: props,
               body: messageBytes);

            cancellationToken.Register(() => callbackMapper.TryRemove(correlationId, out var tmp)); //delegate is called when the token is canceled
            Console.WriteLine(AppConstants.rpcClientMessageSent);
            return tcs.Task;
        }

        public async Task<double> AcquireUserBalance(Guid userId)
        {
            var checkoutUserInfo = new PublishCheckoutUserInfo()
            {
                Id = userId
            };

            var userBalanceRequest = JsonSerializer.Serialize(checkoutUserInfo);
            var balance = await AcquireUserBalanceInfo(userBalanceRequest);
            return double.Parse(balance);
        }
    }
}
